/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.panel.AccountAPIKeyCreateResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.panel.AccountAPIKey');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.panel.AccountAPIKeyCreateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.panel.AccountAPIKeyCreateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.panel.AccountAPIKeyCreateResponse.displayName = 'proto.panel.AccountAPIKeyCreateResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.panel.AccountAPIKeyCreateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.panel.AccountAPIKeyCreateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.panel.AccountAPIKeyCreateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.panel.AccountAPIKeyCreateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    accountApiKey: (f = msg.getAccountApiKey()) && proto.panel.AccountAPIKey.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.panel.AccountAPIKeyCreateResponse}
 */
proto.panel.AccountAPIKeyCreateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.panel.AccountAPIKeyCreateResponse;
  return proto.panel.AccountAPIKeyCreateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.panel.AccountAPIKeyCreateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.panel.AccountAPIKeyCreateResponse}
 */
proto.panel.AccountAPIKeyCreateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new proto.panel.AccountAPIKey;
      reader.readMessage(value,proto.panel.AccountAPIKey.deserializeBinaryFromReader);
      msg.setAccountApiKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.panel.AccountAPIKeyCreateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.panel.AccountAPIKeyCreateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.panel.AccountAPIKeyCreateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.panel.AccountAPIKeyCreateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccountApiKey();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.panel.AccountAPIKey.serializeBinaryToWriter
    );
  }
};


/**
 * optional AccountAPIKey account_api_key = 2;
 * @return {?proto.panel.AccountAPIKey}
 */
proto.panel.AccountAPIKeyCreateResponse.prototype.getAccountApiKey = function() {
  return /** @type{?proto.panel.AccountAPIKey} */ (
    jspb.Message.getWrapperField(this, proto.panel.AccountAPIKey, 2));
};


/** @param {?proto.panel.AccountAPIKey|undefined} value */
proto.panel.AccountAPIKeyCreateResponse.prototype.setAccountApiKey = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.panel.AccountAPIKeyCreateResponse.prototype.clearAccountApiKey = function() {
  this.setAccountApiKey(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.panel.AccountAPIKeyCreateResponse.prototype.hasAccountApiKey = function() {
  return jspb.Message.getField(this, 2) != null;
};


