/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.panel.AccountAPIKeyToken');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.panel.Token');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.panel.AccountAPIKeyToken = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.panel.AccountAPIKeyToken.repeatedFields_, null);
};
goog.inherits(proto.panel.AccountAPIKeyToken, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.panel.AccountAPIKeyToken.displayName = 'proto.panel.AccountAPIKeyToken';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.panel.AccountAPIKeyToken.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.panel.AccountAPIKeyToken.prototype.toObject = function(opt_includeInstance) {
  return proto.panel.AccountAPIKeyToken.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.panel.AccountAPIKeyToken} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.panel.AccountAPIKeyToken.toObject = function(includeInstance, msg) {
  var f, obj = {
    token: (f = msg.getToken()) && proto.panel.Token.toObject(includeInstance, f),
    ipAddressesList: jspb.Message.getRepeatedField(msg, 2),
    description: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.panel.AccountAPIKeyToken}
 */
proto.panel.AccountAPIKeyToken.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.panel.AccountAPIKeyToken;
  return proto.panel.AccountAPIKeyToken.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.panel.AccountAPIKeyToken} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.panel.AccountAPIKeyToken}
 */
proto.panel.AccountAPIKeyToken.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.panel.Token;
      reader.readMessage(value,proto.panel.Token.deserializeBinaryFromReader);
      msg.setToken(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addIpAddresses(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.panel.AccountAPIKeyToken.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.panel.AccountAPIKeyToken.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.panel.AccountAPIKeyToken} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.panel.AccountAPIKeyToken.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getToken();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.panel.Token.serializeBinaryToWriter
    );
  }
  f = message.getIpAddressesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional Token token = 1;
 * @return {?proto.panel.Token}
 */
proto.panel.AccountAPIKeyToken.prototype.getToken = function() {
  return /** @type{?proto.panel.Token} */ (
    jspb.Message.getWrapperField(this, proto.panel.Token, 1));
};


/** @param {?proto.panel.Token|undefined} value */
proto.panel.AccountAPIKeyToken.prototype.setToken = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.panel.AccountAPIKeyToken.prototype.clearToken = function() {
  this.setToken(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.panel.AccountAPIKeyToken.prototype.hasToken = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated string ip_addresses = 2;
 * @return {!Array<string>}
 */
proto.panel.AccountAPIKeyToken.prototype.getIpAddressesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.panel.AccountAPIKeyToken.prototype.setIpAddressesList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.panel.AccountAPIKeyToken.prototype.addIpAddresses = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.panel.AccountAPIKeyToken.prototype.clearIpAddressesList = function() {
  this.setIpAddressesList([]);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.panel.AccountAPIKeyToken.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.panel.AccountAPIKeyToken.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


